[workspace]
resolver = "1"
members = ["utils", "kernel"]

# ==== PROFILES SETTINGS ====
# >> [ Development ]
[profile.dev.package."*"]
opt-level = 0
incremental = true

# >> [ Release ]
[profile.release]
debug = false
codegen-units = 1
opt-level = 3
strip = true
